export class ContainerRuntimeEnvs {
	// Camunda
	public static CAMUNDA_ENV_SPRING_PROFILES_ACTIVE = 'SPRING_PROFILES_ACTIVE'
	public static CAMUNDA_ENV_ZEEBE_CLOCK_CONTROLLED = 'ZEEBE_CLOCK_CONTROLLED'
	public static CAMUNDA_ENV_ZEEBE_LOG_APPENDER = 'ZEEBE_LOG_APPENDER'
	public static CAMUNDA_ENV_CAMUNDA_SECURITY_AUTHENTICATION_UNPROTECTED_API =
		'CAMUNDA_SECURITY_AUTHENTICATION_UNPROTECTEDAPI'
	public static CAMUNDA_ENV_CAMUNDA_SECURITY_AUTHORIZATIONS_ENABLED =
		'CAMUNDA_SECURITY_AUTHORIZATIONS_ENABLED'

	public static CAMUNDA_ENV_CAMUNDA_DATABASE_URL = 'CAMUNDA_DATABASE_URL'
	public static CAMUNDA_ENV_DATABASE_TYPE = 'CAMUNDA_DATABASE_TYPE'
	public static CAMUNDA_ENV_DATABASE_USERNAME = 'CAMUNDA_DATABASE_USERNAME'
	public static CAMUNDA_ENV_DATABASE_PASSWORD = 'CAMUNDA_DATABASE_PASSWORD'

	// Exporter
	public static CAMUNDA_ENV_CAMUNDA_EXPORTER_CLASSNAME =
		'ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_CLASSNAME'
	public static CAMUNDA_ENV_CAMUNDA_EXPORTER_ARGS_CONNECT_URL =
		'ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_CONNECT_URL'
	public static CAMUNDA_ENV_CAMUNDA_EXPORTER_ARGS_BULK_SIZE =
		'ZEEBE_BROKER_EXPORTERS_CAMUNDAEXPORTER_ARGS_BULK_SIZE'

	// H2
	public static CAMUNDA_ENV_ZEEBE_BROKER_EXPORTERS_RDBMS_CLASSNAME =
		'ZEEBE_BROKER_EXPORTERS_RDBMS_CLASSNAME'
	public static CAMUNDA_ENV_ZEEBE_BROKER_EXPORTERS_RDBMS_ARGS_FLUSH_INTERVAL =
		'ZEEBE_BROKER_EXPORTERS_RDBMS_ARGS_FLUSH_INTERVAL'
	public static CAMUNDA_ENV_ZEEBE_BROKER_EXPORTERS_RDBMS_ARGS_DEFAULT_HISTORY_TTL =
		'ZEEBE_BROKER_EXPORTERS_RDBMS_ARGS_DEFAULT_HISTORY_TTL'
	public static CAMUNDA_ENV_ZEEBE_BROKER_EXPORTERS_RDBMS_ARGS_MIN_HISTORY_CLEANUP_INTERVAL =
		'ZEEBE_BROKER_EXPORTERS_RDBMS_ARGS_MIN_HISTORY_CLEANUP_INTERVAL'
	public static CAMUNDA_ENV_ZEEBE_BROKER_EXPORTERS_RDBMS_ARGS_MAX_HISTORY_CLEANUP_INTERVAL =
		'ZEEBE_BROKER_EXPORTERS_RDBMS_ARGS_MAX_HISTORY_CLEANUP_INTERVAL'
	public static CAMUNDA_ENV_LOGGING_LEVEL_IO_CAMUNDA_DB_RDBMS =
		'LOGGING_LEVEL_IO_CAMUNDA_DB_RDBMS'
	public static CAMUNDA_ENV_LOGGING_LEVEL_ORG_MYBATIS =
		'LOGGING_LEVEL_ORG_MYBATIS'

	// Connectors
	public static CONNECTORS_ENV_LOG_APPENDER = 'CONNECTORS_LOG_APPENDER'
	public static CONNECTORS_ENV_CAMUNDA_CLIENT_GRPC_ADDRESS =
		'CAMUNDA_CLIENT_GRPC-ADDRESS'
	public static CONNECTORS_ENV_CAMUNDA_CLIENT_REST_ADDRESS =
		'CAMUNDA_CLIENT_REST-ADDRESS'
}
